### ISSUE TITLE
苹果手机端，经纪人发布二手房，没有“上次交易”属性栏目，网站后台和网站前端是有的。

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#101]
![7](https://cloud.githubusercontent.com/assets/27195858/25416705/cb7a0b16-2a71-11e7-9acc-b9c8aa01a94e.png)
![8](https://cloud.githubusercontent.com/assets/27195858/25416706/cb7b5d9a-2a71-11e7-8ac3-2738dfe10eed.png)

**Comment by abbba** [comment]
安卓同问题

**Comment by rentianhua** [comment]
另外起issue

**Comment by rentianhua** [comment]
代码已经修改，等发布

**Comment by rentianhua** [comment]
等1.3.5发布

**Comment by tanhuan999** [comment]
已经改好了
