### ISSUE TITLE
苹果端，普通用户预约房源成功之后，“新预约”文字没有变成“预约成功”，对比pc端

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#113]
![qq 20170512113914](https://cloud.githubusercontent.com/assets/27195858/25981457/e46dab8a-3707-11e7-879b-e1dab56ba9ef.png)
![qq 20170512113931](https://cloud.githubusercontent.com/assets/27195858/25981459/e4986ed8-3707-11e7-8cf5-b760a7aabe50.png)

**Comment by rentianhua** [comment]
参考#108 中修复的API代码
