### ISSUE TITLE
网站百度的收录的房源信息显示不出图片

### ISSUE THREAD

**Issue by abbba** [rentianhua/tsf#129]
![qq 20170717154421](https://user-images.githubusercontent.com/27986376/28259048-f7158112-6b06-11e7-805d-0cc9312742fe.jpg)
![qq 20170717154428](https://user-images.githubusercontent.com/27986376/28259055-02d7ef12-6b07-11e7-9d06-80798cdc162e.jpg)

**Comment by rentianhua** [comment]
百度收录问题，不属于开发范畴
