### ISSUE TITLE
pc端的地图找房，二手房类型的“更多”筛选，“其他”栏缺少一个属性“唯一住房”

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#18]
![yy](https://cloud.githubusercontent.com/assets/27195858/24999091/d49708fa-206e-11e7-80c2-e44781fdb69a.png)
![yy2](https://cloud.githubusercontent.com/assets/27195858/24999092/d4c2d9c6-206e-11e7-9f95-3e6a376878bf.png)

**Comment by rentianhua** [comment]
code fix refer to #17
