### ISSUE TITLE
苹果端口问题

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#3]
普通用户委托给经纪人的出租房，在经纪人页面的“委托管理”显示这个房源，“出租房管理”也显示该房源。且普通用户的“我要出租”不显示该房源了（手机端和pc端都是这样）
![1](https://cloud.githubusercontent.com/assets/27195858/24890089/709b18d4-1ea0-11e7-88de-240d04532726.png)
![2](https://cloud.githubusercontent.com/assets/27195858/24890093/7130fa84-1ea0-11e7-8ce6-e8d20433bb2b.png)
![3](https://cloud.githubusercontent.com/assets/27195858/24890091/70e5043a-1ea0-11e7-888f-7ea31fdb227f.png)
![4](https://cloud.githubusercontent.com/assets/27195858/24890092/7120ba34-1ea0-11e7-84c8-3683d20a3c37.png)

**Comment by rentianhua** [comment]
我想问的是，这个普通用户知道是谁么？

**Comment by tanhuan999** [comment]
操作步骤：
普通用户登录手机端，发布出租房房源，选择“委托给经纪人”：
![qq 20170411111528](https://cloud.githubusercontent.com/assets/27195858/24891971/ead4bcd0-1eab-11e7-8e78-5ca67ef9791c.png)
![6](https://cloud.githubusercontent.com/assets/27195858/24891981/f7874ccc-1eab-11e7-932e-adb625ff2f2d.png)
进入后台，给委托的出租房选择经纪人之后，审核通过该出租房，经纪人登录手机端，查看“委托管理”的该出租房，并编辑该出租房信息，并提交。
![1](https://cloud.githubusercontent.com/assets/27195858/24892159/f3d2a38c-1eac-11e7-980a-bc2d158eb2b6.png)
![2](https://cloud.githubusercontent.com/assets/27195858/24892158/f3d27c18-1eac-11e7-9415-175b20c8c5b8.png)
查看经纪人的“出租房管理”，发现列表也显示该出租房房源信息。
![8](https://cloud.githubusercontent.com/assets/27195858/24892199/44888116-1ead-11e7-9514-4bd9061c74b8.png)
