### ISSUE TITLE
验证码处理逻辑优化

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#5]
经纪人登录网站前端，删除未使用的优惠券，在弹出的窗口中点击“发送验证码”，收到验证码之后没有输入，等验证码窗口倒计时结束后再一次点击“发送验证码”，收到验证码之后，输入第一次收到的验证码，发现可以删除。
![1](https://cloud.githubusercontent.com/assets/27195858/24944843/6926be10-1f8f-11e7-805e-5028e73eadca.png)

**Comment by rentianhua** [comment]
这个问题是由于验证码没有过期的。原来设计上就没有做

**Comment by rentianhua** [comment]
通问题#76

**Comment by rentianhua** [comment]
关闭此重复的问题
