### ISSUE TITLE
购买优惠券后，手机收到短信的优惠券号不显示。

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#7]
![3](https://cloud.githubusercontent.com/assets/27195858/24948215/32044332-1f9c-11e7-8631-547493bbd061.png)
![4](https://cloud.githubusercontent.com/assets/27195858/24948216/32323b52-1f9c-11e7-8794-d77bc37559dc.png)

**Comment by rentianhua** [comment]
手机端的支付，由于原开发人员的支付接口分为手机端和PC端，之前，解决过PC端的，这个问题是手机端调用接口的问题。
