### ISSUE TITLE
网站前端经纪人页面，筛选条件有问题，操作步骤：先选择除了“房东信赖”的任一个条件，再选择另一个条件，那么出现的结果都是没有的。

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#78]
![1](https://cloud.githubusercontent.com/assets/27195858/25111608/96382306-241e-11e7-9e34-84a3e9b51e93.png)
![2](https://cloud.githubusercontent.com/assets/27195858/25111617/9c32449e-241e-11e7-9f42-1124efa1764e.png)

**Comment by rentianhua** [comment]
由于重复计算了1+2中会重复计算相同的部分，所以1+2会大于3
