### ISSUE TITLE
pc端，二手房房源详情页，为什么“文康楼”小区下面的“同小区成交记录”不显示另一个同小区成交的房源信息。

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#86]
![4](https://cloud.githubusercontent.com/assets/27195858/25119706/da8e777e-244d-11e7-8255-c8f2981d2ff4.png)

**Comment by tanhuan999** [comment]
已解决

**Comment by rentianhua** [comment]
数据库中这个小区只有一套。
