### ISSUE TITLE
苹果手机端，普通用户登录，查看“我的预约”，删除预约房源时发现有些房源提示“锁定”，后台查看该房源并没有锁定。pc端也是这样

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#91]
![5](https://cloud.githubusercontent.com/assets/27195858/25264977/f9e22ac0-269c-11e7-830c-3a10f285af09.png)

**Comment by tanhuan999** [comment]
操作描述：昨天（4-27）我用手机端，登录经纪人账号后，发布一个二手房，发布成功之后。普通用户登录手机端，预约这个房源，预约的时间是今天的9-12点（4-28）。今天上午，我手机端登录经纪人，修改昨天发布的二手房，上传房源图片并提交。下午的时候，普通用户登录手机端，删除该预约二手房信息，发现删除不了，并提示已经锁定了房源。
经纪人账号：15577330719  123456
普通用户的账号：15577124731   1234567
发布的二手房：http://www.taoshenfang.com/index.php?a=shows&catid=6&id=581

**Comment by tanhuan999** [comment]
手机端确认功能：关于1.当经纪人确认了预约房源，且房源预约没有过期。
2.当经纪人确认了预约房源，且房源预约已经过期。
3.当经纪人没有确认预约房源，且房源预约已经过期。
修改成：设置普通用户的“看房行程”不可以进行“删除”预约房源操作，添加“取消预约”功能。无论经纪人有没有确认预约，普通用户都可以取消预约的房源，普通用户点击“取消预约”按钮后，页面会显示“已取消”文字，经纪人的“带看行程”对应的这条预约会提示“已取消”。且，如果房源过期了，那么不可以进行“取消预约”功能。
这里针对的不仅仅是普通用户预约经纪人的二手房，还有普通用户预约普通用户的二手房。
普通用户取消另一个普通用户的二手房预约，那么普通用户的“带看行程”对应的这条预约会提示“已取消”。
![1](https://cloud.githubusercontent.com/assets/27195858/25647334/b0aca5a0-2ff3-11e7-84af-a174a1ad9c49.png)
![2](https://cloud.githubusercontent.com/assets/27195858/25647335/b0ccc43e-2ff3-11e7-8579-6b6ca6354472.png)
![3](https://cloud.githubusercontent.com/assets/27195858/25647337/b1411cc6-2ff3-11e7-8ba6-a78527a80797.png)
![6](https://cloud.githubusercontent.com/assets/27195858/25647336/b118003e-2ff3-11e7-8dd7-9cc8bbfa4691.png)

**Comment by rentianhua** [comment]
待发布
