### ISSUE TITLE
网站前端，地图找房的二手房，盐田港显示没有房源，实际上是有的，在二手房页面可以查找得到，手机端也有。

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#92]
![11](https://cloud.githubusercontent.com/assets/27195858/25325734/97e3fc1c-28ff-11e7-9e51-825953296701.png)
![22](https://cloud.githubusercontent.com/assets/27195858/25325735/97fa1dbc-28ff-11e7-80b4-2d43544344e3.png)
![33](https://cloud.githubusercontent.com/assets/27195858/25325812/e6e42788-28ff-11e7-8fd4-7de29ce5dec0.jpg)

**Comment by rentianhua** [comment]
经过测试，无法重现问题。
