### ISSUE TITLE
苹果手机端，无论是经纪人还是普通用户，页面都没有“购房计算器”，安卓是有的。

### ISSUE THREAD

**Issue by tanhuan999** [rentianhua/tsf#98]
![1](https://cloud.githubusercontent.com/assets/27195858/25416099/851fda36-2a6e-11e7-9f6d-10662b80c79e.png)

**Comment by tanhuan999** [comment]
安卓的购房计算器
![qq 20170512111447](https://cloud.githubusercontent.com/assets/27195858/25980878/3e172840-3704-11e7-9b12-91b3219840c0.jpg)
![qq 20170512111453](https://cloud.githubusercontent.com/assets/27195858/25980879/3e1b8426-3704-11e7-87af-f874ebf52d93.jpg)

**Comment by rentianhua** [comment]
待发布

**Comment by tanhuan999** [comment]
已改好
